ceneo_options:
    path:     /
    defaults: { _controller: CeneoBundle:Options:index }

ceneo_xml:
    path:     /hash/{shopId}
    defaults: { _controller: CeneoBundle:Generator:download }

ceneo_exclusions:
    path:     /exclusions
    defaults: { _controller: CeneoBundle:Exclusions:index }


ceneo_exclusions_delete:
    path:     /exclusions/{id}
    defaults: { _controller: CeneoBundle:Exclusions:delete}