ceneo_options_compat:
    path:     /
    defaults: { _controller: CeneoBundle:Options:index }

ceneo_options:
    path:     /options
    defaults: { _controller: CeneoBundle:Options:index }

ceneo_xml:
    path:     /xml/{shopId}.xml
    defaults: { _controller: CeneoBundle:Generator:dummy }

ceneo_xml_force:
    # cheat httpd
    path:     /xml/force/{shopId}.xml
    defaults: { _controller: CeneoBundle:Generator:download }

ceneo_exclusions:
    path:     /exclusions
    defaults: { _controller: CeneoBundle:Exclusions:index }

ceneo_exclusions_add:
    path:     /exclusions/add
    defaults: { _controller: CeneoBundle:Exclusions:add }