parameters:
    xml_dir: %kernel.root_dir%/web/ceneo/xml

services:
    cache:
        class: Doctrine\Common\Cache\ApcCache

    ceneo.export_checker:
        class: CeneoBundle\Services\ExportChecker
        arguments: [@doctrine.orm.entity_manager]

    ceneo.appstore_listener:
        class: CeneoBundle\EventListener\AppstoreListener
        arguments: [%xml_dir%]
        tags:
            - { name: kernel.event_listener, event: dream_commerce_shop_appstore.uninstall, method: onUninstall }