root:
    #resource: "@DreamCommerceShopAppstoreBundle/Resources/config/routing.yml"
    resource: "@DreamCommerceShopAppstoreBundle/Resources/config/routing.xml"

ceneo:
    resource: "@CeneoBundle/Resources/config/routing.yml"
    prefix:   /

