ceneo_options_compat:
    path:     /
    defaults: { _controller: CeneoBundle:Options:index }

ceneo_options:
    path:     /options
    defaults: { _controller: CeneoBundle:Options:index }

ceneo_xml:
    path:     /xml/{shopId}.xml
    defaults: { _controller: CeneoBundle:Download:download }

ceneo_exclusions_add:
    path:     /exclusions/add
    defaults: { _controller: CeneoBundle:Exclusions:add }

ceneo_exclusions:
    path:     /exclusions/{page}
    defaults: { _controller: CeneoBundle:Exclusions:index, page: 1 }

ceneo_mappings:
    path:     /mappings
    defaults: { _controller: CeneoBundle:Mappings:index }

ceneo_mappings_group:
    path:     /mappings/{group}
    defaults: { _controller: CeneoBundle:Mappings:group }

ceneo_status_check:
    path:     /status_check
    defaults: { _controller: CeneoBundle:Generator:checkStatus }

ceneo_enqueue:
    path:     /enqueue
    defaults: { _controller: CeneoBundle:Generator:enqueue }