parameters:
    xml_dir: %kernel.root_dir%/../web/ceneo/xml

services:
    cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: [%kernel.cache_dir%]

    ceneo.export_status:
        class: CeneoBundle\Services\ExportStatus
        arguments: [%xml_dir%, @doctrine.orm.entity_manager]

    ceneo.appstore_listener:
        class: CeneoBundle\EventListener\AppstoreListener
        arguments: [%xml_dir%, @doctrine.orm.entity_manager, @ceneo.export_status]
        tags:
            - { name: kernel.event_listener, event: dream_commerce_shop_appstore.uninstall, method: onUninstall, priority: 1 }

    ceneo.fetchers_categories:
        class: CeneoBundle\Services\Fetchers\Categories
        arguments: [%categories_ttl%, @cache]

    ceneo.test_worker:
        class: CeneoBundle\Worker\TestWorker
        arguments: [@logger]

    ceneo.attribute_group_mapping_repository:
        class: CeneoBundle\Entity\AttributeGroupMappingRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - CeneoBundle\Entity\AttributeGroupMapping

    ceneo.excluded_product_repository:
        class: CeneoBundle\Entity\ExcludedProductRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - CeneoBundle\Entity\ExcludedProduct

    ceneo.queue_manager:
        class: CeneoBundle\Services\QueueManager
        arguments: [@gearman]

    ceneo.generator:
        class: CeneoBundle\Services\Generator
        arguments: [%xml_dir%, @cache, @ceneo.excluded_product_repository, @ceneo.attribute_group_mapping_repository, @ceneo.export_status]
        calls:
            - [setStopwatch, [@debug.stopwatch]]

    ceneo.generator_worker:
        class: CeneoBundle\Worker\GeneratorWorker
        arguments:
            - %xml_dir%
            - @dream_commerce_shop_appstore.ceneo
            - @ceneo.generator
            - @ceneo.export_status
            - @doctrine.orm.entity_manager
